#define USB_VENDOR_ID_CORSAIR					0x1b1c

#define USB_DEVICE_ID_CORSAIR_VOID_WIRELESS			0x1b27
#define USB_DEVICE_ID_CORSAIR_VOID_PRO				0x0a14
#define USB_DEVICE_ID_CORSAIR_VOID_PRO_R2			0x0a16
#define USB_DEVICE_ID_CORSAIR_VOID_PRO_USB			0x0a17
#define USB_DEVICE_ID_CORSAIR_VOID_PRO_USB_2			0x0a1d
#define USB_DEVICE_ID_CORSAIR_VOID_PRO_WIRELESS			0x0a1a
#define USB_DEVICE_ID_CORSAIR_VOID_RGB_USB			0x1b2a
#define USB_DEVICE_ID_CORSAIR_VOID_RGB_USB_2			0x1b23
#define USB_DEVICE_ID_CORSAIR_VOID_RGB_USB_3			0x1b29
#define USB_DEVICE_ID_CORSAIR_VOID_RGB_WIRED			0x1b1c
#define USB_DEVICE_ID_CORSAIR_VOID_RGB_WIRELESS			0x0a2b
#define USB_DEVICE_ID_CORSAIR_VOID_RGB_ELITE_WIRELESS		0x0a51
#define USB_DEVICE_ID_CORSAIR_VOID_RGB_ELITE_WIRELESS_PREMIUM	0x0a75
#define USB_DEVICE_ID_CORSAIR_VOID_ELITE_USB			0x0a52
#define USB_DEVICE_ID_CORSAIR_VOID_ELITE_WIRELESS		0x0a55
#define USB_DEVICE_ID_CORSAIR_VOID_ELITE_RGB_USB		0x0a56
